version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: node:20
    auth:
      username: santhosh270
      password: Catalyst@test123
jobs:
  Deploy_Client_Functions:
    runner: Machine
    image: image
    steps:
      - npm install -g vercel
      - vercel --version
      - vercel --token=DWkAIYRcGfsaZqkJmK2LtD3u --yes
stages:
  - name: test
    jobs:
      - Deploy_Client_Functions
variables:
  VercelToken: DWkAIYRcGfsaZqkJmK2LtD3u