version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: ubuntu:latest
    auth:
      username: santhosh270
      password: Catalyst@test123
jobs:
  Deploy_Client_Functions:
    runner: Machine
    image: image
    steps:
      - npm install axios
stages:
  - name: build
    jobs:
      - Deploy_Client_Functions